logging:
  level:
    root: INFO
    com.bol.kalaha.api: DEBUG

server:
  port: 8080

spring:
  application:
    name: ms-kalaha-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kalaha_game_db
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher